#!/usr/bin/env python
import sys,os
try:
    import configparser as cp
except:
    import ConfigParser as cp   # python 2.x
import subprocess as sp
sys.path.insert(0,os.getcwd())
import git

program_name = "git-hq"

class Repo(object):
    def __init__(self,name,id,repos):
        self.name = name
        self.id = id
        self.repos = repos

def load_config(file):
    c = cp.RawConfigParser()
    c.read(file)

    remotes = dict(c.items('remotes'))

    sections = c.sections()
    sections.remove('remotes')
    
    repos = {}

    for s in sections:
        p = dict(c.items(s))    # p=properties
        repos[p['id']] = Repo(s,p['id'],
                              [remotes[r].replace("{}",s) for r in p['repos'].split(',')])
    return repos

def identify_current_repo(repos):
    for h in git.hashes():
        if(h in repos):
            return repos[h]
    return None

def identify_desired_repo(repos,name):
    try:
        return next(r for k,r in repos.items() if r.name==name)
    except StopIteration:
        return None

def suggest():
    try:
        print("""Add the following to ~/.%s to include this repo
[%s]
id=%s
repos=...""" % (program_name, git.name(), git.last_hash()) )
    except sp.CalledProcessError:
        print("""Add repo information to ~/.%s or run in existing repository""" %
              program_name)

def cmd_help(repo=None,args=None):
    print("""usage: %s <command>
commands available include:
\tpull
\tpush
\thelp""" % program_name)

def pull(repo,args=None):
    git.cmd('pull',repo.repos[0])

def push(repo,args=None):
    for r in repo.repos:
        git.cmd('push',r)

def clone(repo,args=None):
    git.cmd('clone',repo.repos[0])

def main(*argv):

    if (len(argv) < 2):
        cmd_help()
        return 0

    try:
        repos = load_config(os.getenv("HOME")+"/."+program_name)
    except IOError:
        print("fatal: no ~/."+program_name+" config file found")
        return 1

    # check if we can even get repo info...
    exists = git.exists()
    # obtain repo info if so
    repo = identify_current_repo(repos) if exists else None
    # if user was trying to create a repo, look it up in config
    desired_repo = (identify_desired_repo(repos,argv[2]) if 
                    (len(argv) > 2) and not exists else None)

    # handle error cases
    if repo is None and desired_repo is None:
        print(program_name+": no repository found or not in config file")
        return 1
    elif exists and repo is None:
        print(program_name+": git repository not in config file")
        suggest()
        return 1

    if repo is None:
        repo = desired_repo

    verbs = {'clone':clone, 'pull':pull, 'push':push, 'help':cmd_help}

    try:
        verbs[argv[1]](repo,argv[2:])
    except KeyError:
        print(program_name+": "+argv[1]+" is not a "+program_name+" command. See 'git hq help'.")

    return 0
 
if __name__ == '__main__':
    sys.exit(main(*sys.argv))
